### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by lhorie** [trackira/trackira#1]
Hi, Mithril.js author here.

Spent a couple of minutes w/ Trackira. Here's some observations:

- Example in readme throws error because it's using `trackira` (lower case). File in `/dist` exposes `Trackira` (uppercase)

- Couldn't get keys to work. Test case:

```javascript
var items = [
	{id: 1, name: "a"},
	{id: 2, name: "b"},
	{id: 3, name: "c"}
]
function reverse() {
	items.reverse()
	Trackira.update(rootNode, root)
}

function root() {
	return {tag: "div", children: items.map(function(item) {
		return {
			tag: "input",
			key: item.id, //maybe here?
			attrs: {
				key: item.id, //or here?
				value: item.name
			}
		}
	})}
}


var rootNode = Trackira.append(document.body, root);

setInterval(reverse, 2000)

//click on first input
//expected: focus should jump to third input after 2 seconds, then back to first input after 2 seconds, etc
//actual: focus is lost
```

- are there events for mounting / unmounting elements?

- is it possible to get granular control over a diff? (i.e. React's shouldComponentUpdate / Mithril's subtree directives)

- `Trackira.append(document.body, [root])` didn't work and didn't throw errors.

- Requiring the DOM element as an argument of update makes code harder to reuse, especially w/ browserify

- do you handle spam redraws? Mithril's anti-spam heuristics are [fairly complex](http://lhorie.github.io/mithril/auto-redrawing.html), and one of the reasons why it does well when benched against Backbone doing naive always-redraw-on-update

Cheers.

**Comment by Kflash** [comment]
@lhorie  Hi. First off I have to admit there are still issues here and there to fix, and therefor I use the word *experimental* all over. 

* Regarding the example not working, it's a typo. I changed the uppercase letter for Trackira last night, but didn't change it in the readme. Will do ASAP.

* For mounting / unmounting elements, and grunular control, I'm not there yet. I'm one developer, but have it on my todo list. My main focus lately have been to support a REACT compliant virtual DOM object that can be used both for React.render() and Trackira.render(). 

* regarding spam I'm not there yet. So far my focus have been on preventing XSS attacks. 

But I become curious when you mention that **append()** are not working? 

Regarding keys not working, they seems to work just fine in my end:

```javascript

// Javascript code

var items = [
    {id: 1, name: "a"},
    {id: 2, name: "b"},
    {id: 3, name: "c"}
]
function reverse() {
    items.reverse()
    Trackira.update(rootNode, root)
}

function root() {
    return {
        
        tag: "div", children: items.map(function(item) {
        return {
            tag: "input",
            attrs: {
                key: item.id, //or here?
                value: item.name
            }
        }
    })}
}
var rootNode = Trackira.append(document.body, root);

// Console log
<div>
<input key="1">
<input key="2">
<input key="3">
</div>
```

**Comment by Kflash** [comment]
@lhorie Trackira now fully works with life cycle events - *created*,  *changed*, *destroyed*, *created*, and you can use them as this:

```javascript
 var node = Trackira.render({
                tag: 'div',
                events: {
                    $changed: changedHandler
                }
            });
```
For rendering I now activated a couple of more functions. You can use the **append() API** method for this. A callback for the child nodes.

```javascript
    children: function (oldChild) { ... }
```
The oldChild is only defined if the node was added to the DOM in a previous cycle. So a boolean true / false you can check against. If no changed, it will keep the subtree as it is.
