### ISSUE TITLE
[Q] Verbosity

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#45]
Hi!
To my taste `new Trackira.Element("div", ..` is too verbose. Do I understand correctly you leave wrapping element creation with function (resulting, say, in `t("div", ..` to Trackira user?

**Comment by Kflash** [comment]
Hi. I understand your point of view. And to answer you. Yes and no. ``` new Trackira.Element() ``` is never ment to be used directly. Same with ``` Text() ``` and ```Comment()```. This is low-level library, and should be used together with a ```hyperscript``` method, or a component library. The end-result would become something like what you suggest ``` t("div"); ```

There is no ```hyperscript``` in Trackira, but you can take a look here: https://github.com/trackira/trackira/blob/master/test/tools/tools.js#L17-L33

**Comment by gaydenko** [comment]
I guess this verbosity exposed in README can reduce library adoption. We all are in a hurry :), and quick look at the example would be more pleasure and appealing with more compact code on the first place.

**Comment by Kflash** [comment]
So what you suggest? Adding a ```hyperscript``` function as a module, and use it in the README such as 
` h("div") `? I will look into it.

**Comment by gaydenko** [comment]
Yes, thanks. 
Will we keep the issue open for a while?

**Comment by Kflash** [comment]
Sure, and a hyperscript function will be up in 3 minutes.

**Comment by gaydenko** [comment]
Aha, I see changes in repo. What do you think if to add `var h = Trackira.h;` at the beginning of the first code fragment in README, and then to leave just `h("div", ..` in all following code fragments?

**Comment by Kflash** [comment]
Sound great. I can try to solve that after I'm finnish with digging into the client side issues. Or do a PR if you want.

**Comment by gaydenko** [comment]
There isn't any hurry, so I would prefer the first suggestion :)

**Comment by Kflash** [comment]
I updated the readme again with your suggestions in mind. I asked my companion to change the jsfiddle when he wakes up.

**Comment by gaydenko** [comment]
@Kflash , I'm afraid you will beat me, but I still have few thoughts related to further verbosity reduction :)

- what if to replace `targName` with `tag?
- children autoboxing: what if `[ h(1), h("abd") ]` can be written as `[ 1, "abd" ]`?
- what if `h(obj, [ ch1, ch2, ch3 ])` can be written as `h(obj, ch1, ch2, ch3)`?

**Comment by gaydenko** [comment]
@Kflash , I have tried the second item in code (children autoboxing), and it is already there :)

**Comment by Kflash** [comment]
@gaydenko I will look into this in a few hours. TagName renamed to tag isn't a huge issue.  But your last point are complex.  All children needs to be an array. Else say you to this:

`h ({tagname:"div"}, ch1)`

`ch1` will be seen as an text node. 

`h ({tagname:"div"}, "Hello")`
Let you create a virtual node with one virtual text node as a child.

**Comment by gaydenko** [comment]
@Kflash , I guess "autoboxing into array" can be applied just for cases when `h` has got more than two arguments (the first is an object, and the rest two or more are wrapping into array).

**Comment by Kflash** [comment]
I will fix something in a few hours. Btw. Have you used Trackira for some
projects? This days I'm on and off because of my vacation in a foreign
country. But will fix things rapidly as I can. Now I vanish again...

**Comment by gaydenko** [comment]
@Kflash , I just try to understand the best way to convert presentation layer of a mid-size project (it's startup already running in production) from structures based on, at first, knockout.js, now - on vue.js, and will be based on something based on vdom, as far as those packages with templating/binding are too bloated and sometimes magic (I mean heavy project-wide using of promises in the project and not obvious steps to integrate with those libraries). 

Of course, there are other (not so large) aspects on the client-side rewriting.

Digging last days here and there I have got a willing to try two projects - Trackira and cito.js. The last one is at heavy rewriting now, as I can understand, so the Trackira is the first :) Upcoming days (probably starting from tomorrow) I'll start to play with presentation code (there are other infrastructure things I"m modifying also at the moment).

@Kflash , you are very responsive, fast and friendly, and it is really great, thanks! Of course, I can not (and will not) expect you will always immediately react on the users' feedback. Let it be as is, and let code hacking will get us as more pleasure as it can :)

**Comment by Kflash** [comment]
@gaydenko As an habbit I have, I never talk negative or positive about other repos on Github. But you mentioned citoJS. Did you know that he has done re-write since march? And nothing yet. But far as I understand it will be template like. 
When it comes to Trackira, it is what you see today, but after my vacation something are going to change........... not more to say about it then I guess i will do a `knockout` on the libs you listed here.
And I guess you know already you can render all HTML server-side with Trackira, and do only updates on client-side? And also embed exicting HTML markup into a already rendred DOM tree? And no magic at all. You do:

```var html =  new Trackira.Element("div", {attrs: id:"hello"}).toHTML(); ```

After many years as a developer, it become naturall to be fast and friendly :) You learn fast that not all people are equal and understand the same things as you do.

**Comment by gaydenko** [comment]
@Kflash , yes, it seems that project is going to merge with t7, and (if it's the fact) it is an absolute reason to be excluded for the pretenders list. And, as I said, at any case I'm starting with Trackira and hope it will fulfill all project aims (I haven't too many time to ramble between different vdom implementations). So there is an high probability I will tire you with feedback :)

I use Scala on the server side, so I prefer all presentation work do on the client side (even having own simple but sufficient templating on the server side).

**Comment by Kflash** [comment]
@gaydenko I was looking into this now, and decided nothing will be changed atm. This because of the upcoming changes. Just now I have to spend the time stabilize everything.

**Comment by gaydenko** [comment]
@Kflash , OK, I see, closing for now.

I have mostly shared the essence of own vision at presentation layer (and at generally doing mistake - at least as I guess) here: https://github.com/joelrich/citojs/issues/18#issuecomment-120488735

OK, I'll immediately notify you would meet some show stoppers or just unhandy API details. And, of course, I'm ready to answer any you question about my use case via gmail account andrew.gaydenko , would such question will arise.

I share your opinion regarding library aim: to be the fastest (or the smallest, or the widest or any other ..est) isn't that I feel to be natural. To my taste, minimal (or zero if possible) deps, predictability, and clean code organization are features we can not sacrifice. Gold mix of compromises is that receipt we are all looking for  :)

**Comment by gaydenko** [comment]
@Kflash , 
There is another simple opportunity to make hyperscripting a bit more concise:
```js
// at the moment:
events: {onclick: toggle}
// suggested Edem:
on: {click: toggle}
```
That is to rename `enents` to `on` and to remove `on...` prefix from events' names. What do you think?

**Comment by Kflash** [comment]
Well, you don't need to use the on prefix. It should work with a simple
"click". For events to on? Events are used as a collection name for a serie
of different events. And if a "on" there should be an "off" too, but there
is no "off" in Trackira.

**Comment by gaydenko** [comment]
OK, skipping it :)

**Comment by gaydenko** [comment]
@Kflash , `click` doesn't work for me, `onclick` does.

**Comment by Kflash** [comment]
Can you provide a example code?

**Comment by gaydenko** [comment]
The test case is heavy integrated in the modules framewrok, so it is impossible to pull it as self-contained example. But the issue is reproducible here

http://jsfiddle.net/jpyr2ksL/54

if replace script ref with https://raw.githubusercontent.com/trackira/trackira/master/dist/trackira.js - that is current version.

**Comment by Kflash** [comment]
I'm see what you want to archive. I'm looking into that soon

**Comment by Kflash** [comment]
I see what you want now. "onclick" to be "click". Reason I did this the first place is to be equal to the HTML properties ( DOM Level 0 ): ```  props: { onclick: function() {} } ```
and then a equalent for events:
``` events: { onclick: function() {} } ```

**Comment by Kflash** [comment]
@gaydenko I did a quick fix. Can you test if this is what you need?

**Comment by gaydenko** [comment]
OK, I see. 
I guess, both `on` as relation to event binding and brief form of events' names (`on` is truncated) are already widely spread idioms, and are absolutely transparent for all community :)

Yes, I have decided to move form template-based solution to VD, but, say, vue.js, the best (to my taste, of course) library on that class (that it template-based) has got this concise form:
```html
  <a v-on="click: onClick">Trigger a handler</a>
```
So, from perspective of new adopters moving from template-based solutions to virtual DOM solutions extraneous verbosity would be treated of some kind of loss, I guess.

**Comment by gaydenko** [comment]
> Can you test if this is what you need?

I will and report.

**Comment by gaydenko** [comment]
@Kflash , yes, `on` truncating does work for me. thanks!

**Comment by Kflash** [comment]
@gaydenko Not a problem :) You can see here what I did and how: https://github.com/trackira/trackira/blob/master/src/Element/events/shared/genericHandler.js#L14

**Comment by gaydenko** [comment]
@Kflash , as I have reported, `click` does work for me, thanks!
