### ISSUE TITLE
build/test error: jsdom 4.x onward only works on io.js

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#46]
Hi!

On building/testing I get `jsdom 4.x onward only works on io.js, not Node.js..`
Node.js in use:
```
trackira $ node -v
v0.12.7
```

**Comment by Kflash** [comment]
This is atm only compatible with iojs. If you want to build this for nodejs, you need to change to ``` jsDom v. 3.x.``` 
This will be changed in the next major release of nodeJS I think. See this article:
http://thenextweb.com/dd/2015/06/16/node-js-and-io-js-are-settling-their-differences-merging-back-together/

**Comment by gaydenko** [comment]
Probably I have missed something, but both io and node started to merge, and the last one is wider spread, so in perspective I don't see any advantages to use io. Again, may be I"n wrong. So, closing :)
