### ISSUE TITLE
[Q] terms expectation

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#48]
HI! English isn't my native language, and, as a result, my case can be far from being general enough. When I firstly have looked at

```
{
 key: String|Integer
 props {}
 attrs: {}
 events: {}
 callbacks: {}
}
```
~~~, my brain immediately asked me: "well, 'events' is just binding DOM events, - say, form submission - to callbacks. Then, what does 'callbacks' mean?".~~~

~~~So, to my not-English taste :) the word 'events` is better to use for denoting DOM events binding, and lifecycle hooks can be named some other way (may be just 'hooks' as in Snabbdom is did and, probably, is the most expected way).~~~

What do you think?

Edit: it was my error. In fact I just suggest to rename `callbacks` to `hooks`, as far as `callbacks` are associated with binding to DOM events.

**Comment by deamme** [comment]
@gaydenko You want to rename "callbacks" to "hooks"? I personally think that's better. @Kflash is soon back on track, let us see what he thinks.

**Comment by gaydenko** [comment]
@deamme , I'd prefer

- `callbacks` rename to `events`,
- `events` rename to `hooks`

I guess this wording would be more expected by new adopters.

**Comment by deamme** [comment]
@gaydenko I would be confused by that. When I see "events" then I think about DOM events binding.. Right now "events" is just like that.

**Comment by gaydenko** [comment]
@deamme , ah, yes, my fault! Sorry. Yes, I suggest to rename `callbacks` to `hooks`, as far as `callbacks` we already use to bind to DOM events.

**Comment by Kflash** [comment]
@gaydenko @deamme I'm here now. Check out the latest upload. Is that what you both want?

**Comment by gaydenko** [comment]
@Kflash , yes, thanks! :+1: 
@deamme , can I'm ready to close the issue, the fruit is in hands :)
