### ISSUE TITLE
callbacks array

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#49]
Hi! 

I guess it may be handy to permit using of functions array on places where a single callback is currently expected  (that is inside `events` and `hooks` objects), of course, keeping the case with single callback as is.

**Comment by Kflash** [comment]
Could you provide an example use case? Something like the factory function for mounting and children?

**Comment by gaydenko** [comment]
@Kflash , for example, a lifecycle event results in some visual feedback effect and some application (server side) action. Yes, it is possible to merge them in a new function (or inline function), but an array represents intention more clear (that is more readable) to my taste. Of course it is very minor suggestion.

**Comment by Kflash** [comment]
@gaydenko Can you provide a code example / illustration? I didn't get you 100%. So I can deep dive into this as soon as I get time. A 'hook' on Trackira is not just a 'hook'. You can use the hooks to trigger visual feedback, or even update a second DOM tree if you do something on the first DOM tree.

**Comment by gaydenko** [comment]
@Kflash , say, on some subtree update I'd want to apply a visual effect (for example - "wink", that is fast fade-out with immediate fade-in) and notify piwik about some action:

`created: [ effects.wink, piwik.notify('cool update happend') ]`

(of course, the last function call returns function). You see, these actions are from parallel universes having nothing common.

**Comment by Kflash** [comment]
@gaydenko and then it was this task then... It's the middle of the night here now, but shit ... I'm working

**Comment by gaydenko** [comment]
@Kflash , what is your local time? I have 03:42 here :)

**Comment by Kflash** [comment]
2.45 AM now. I'm on vacation in Denmark. I have no problems working at night, because my original locale time are 8.46AM if I'm at home.

**Comment by Kflash** [comment]
@gaydenko I think maybe best to move to a higher level of abstraction? You would need iteration and methods that slow things down, AND not VD related

**Comment by gaydenko** [comment]
@Kflash , OK, let's h()` be a bit cleaner :)

**Comment by gaydenko** [comment]
@Kflash , by the way, have you any own further plans with regard to hyperscript syntax? The thing is, `h()` is supposed to be the most used function, and it's API finalizing is the main finalizing :)

**Comment by Kflash** [comment]
@gaydenko Not at the moment, but I can change it radpidly if any suggestions.

**Comment by gaydenko** [comment]
@Kflash , I think about mithril.js signature, where the first argument is a string (the next is ab object, and the last is children), and the string is css-like selector. At case a tag is omitted in the string (that is id and static classes are listed only), default tag is used (say `div` or `span`, may be configurable). I guess the way is type-saving and visually appealing, resulting in more concise and readable code. What do you think?

**Comment by Kflash** [comment]
@gaydenko Mithril is a framework, and Trackira is a low-level library. It's main purpose is to be used with a higher level of abstraction - a component layer etc. 
I understand what you suggestion, but you will not be able to:

- mount in the same way as now
- hard to get your unique ID with mounting
- .toHTML() for server side rendring and HTML markup will not be done
- some major Tree functions can't be done

and the list goes on...

**Comment by gaydenko** [comment]
> After my vacation I will release a replacement that will take care of all this things, and also replace hyperscript.

@Kflash , are you going replace `h()` implementation only? That is will API be kept the same?

**Comment by Kflash** [comment]
API will remain the same. From Monday I'm not around for awhile before I'm
back again end of month. Heading to Moscow before I return home.

**Comment by gaydenko** [comment]
> API will remain the same

@Kflash , I see, great! 

Good luck in you trip!
