### ISSUE TITLE
[Q] tree's methods hooks

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#50]
Hi!

To integrate Trackira in the project in hands I need to know when tree's methods (mount, update, unmount) result in DOM subtree update. Are these method synchronous (that is return when DOM is updated)? If it isn't the case - are there any hooks for "DOM is updated" event?

**Comment by Kflash** [comment]
@gaydenko  If you take a look at the readme - https://github.com/trackira/trackira#hooks--lifecycle-hooks

There is an updated hooks mentioned, is that the same?

**Comment by gaydenko** [comment]
At point where `tree.update()` is called I have vnode reference only (as well as mountId, of course) returned by somebody else. In other words, vnode creation is abstracted in that point.

**Comment by Kflash** [comment]
You have seen this? https://github.com/trackira/trackira/blob/master/test/specs/hooks.spec.js#L32-L56

**Comment by gaydenko** [comment]
@Kflash , sorry, can not catch how that fragment is related to the question. Probably, some things seeming obvious for you are yet magic for me :)

**Comment by Kflash** [comment]
@gaydenko  You need to update a DOM node with another DOM node, and get the result with hooks? Attach the 'updated hook' on the created virtual DOM node, patch with mounted node, or a real DOM node. And you should get it, or I miss something? The hook are triggered everytime you patch / trigger.

**Comment by gaydenko** [comment]
@Kflash , let's take the first example in the README.md. The second from the end string is
 `tree.update(mountId, vnode);`
I'd want to do something after the DOM finished updating, say, to emit a message:
```js
tree.update(mountId, vnode);
bus.emit('updated, user is happy!');
```
So the question is: can I be sure DOM is already updated at the moment a message is emitted? And let's imagine the code inside `setInterval` is called in place where we have `vnode` reference (or `reneder()` one) only, that is beyond topmost `h()` embracing `vnode` (that is `render()`) definition.

**Comment by Kflash** [comment]
@gaydenko Now think I understand what you want.  You can be sure of this, but use a 3rd arg. On update. I will come back to this very soon, need to fix something inside the code. And you will get a example too.

**Comment by gaydenko** [comment]
Great, I'm on-line!

**Comment by Kflash** [comment]
Have a look: https://github.com/trackira/trackira/blob/master/test/specs/mount.spec.js#L89-L145

**Comment by gaydenko** [comment]
@Kflash , yes, I see thanks for the example. On that example on mounting we just stick a mount point to a given `render()` function (binding to Foo instance context). Unfortunately, I ask something else :) I'm interested exclusively in synchronous or asynchronous nature of `update()`. Say, `$.ajax(url)` returns immediately, but doesn't return anything interested for us, and we use callbacks. `fetch(url)` returns immediately, but it returns `Promise` instance, and we use a chain of `than()`s to deal with promises. The same way I'm interested in `tree.update()`: is there guarantee a browser's DOM us fully updated on the function return? That is, is `update()` synchronous?

**Comment by Kflash** [comment]
The browsers DOM - or at least the DOM tree you are mounting - will always be up-to-date as long as you are using the unique identifier to do your updates. During each mount everything is stored in a object: 
https://github.com/trackira/trackira/blob/master/src/Tree/prototype/apply.js#L41-L47

So the DOM tree will always be the same as you mounted it as. However, when you do an update, it's children will be replaced with the updated children, but still will be the same. Except you are doing an manual refresh of the webpage.

So at anytime, the virtual DOM tree you are mounting will be the same.

More advanced then this belongs to a higher level of abstraction.

**Comment by gaydenko** [comment]
@Kflash , aha, in other words these tree's functions are synchronous, thanks! The thing is, I'm not deeply aware of that internal DOM mechanics and, as a result, don't know sync/async nature of those DOM mutations :) Thanks!

**Comment by Kflash** [comment]
@gaydenko Yup, and I also updated the answer to you with a not documented feature.

**Comment by gaydenko** [comment]
@Kflash , thanks. 
`mounted()` is handy :)

**Comment by Kflash** [comment]
@gaydenko Just grab my latest update. I added two functions that may help you: `children()` and `mountPoint` for the mounting process.

**Comment by gaydenko** [comment]
At the moment I'm not so far in code to immediately catch a way to use them, but at any case - thanks, the train is moving... :)

**Comment by Kflash** [comment]
@gaydenko The whole code got a performance boost now, and the Tree process should be faster and better. Improved performance for FF, and handhold devices. So grab the latest if you are using Trackira in your project??

**Comment by gaydenko** [comment]
@Kflash ,
Yes, thanks, I'm subscribed to Trackira changes and follow them in my package.json.

**Comment by Kflash** [comment]
@gaydenko Today I finished what I was doing the last days regarding virtual tree and mount / unmount.
Have a look at this issue for futher info: https://github.com/trackira/trackira/issues/52

**Comment by gaydenko** [comment]
@Kflash , OK, I see, thanks!

...and good luck in my country :)
