### ISSUE TITLE
[Q] When and how to use patch()?

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#51]
Hi! Can not grok when and how to use `Trackira.patch()`. Some additional hints in `README.md` about appropriate use cases and examples in `/demo` would be very helpful for new adopters, I guess.

**Comment by Kflash** [comment]
`Trackira.patch()` are more or less not a function you don't need to use. It's used internaly when you patch a DOM node. Equalent for `Trackira.patch()` are `Trackira.patch()`. Last one handle factories and arrays of children as well. Anyhow. 

Main purpose for both API methods to update it's children on a real DOM node. 

Take a look at this spec:
https://github.com/trackira/trackira/blob/master/test/specs/core/keys.spec.js#L293-L303

**Comment by Kflash** [comment]
@gaydenko I updated the readme, and maybe you got a few suprises there now.

**Comment by gaydenko** [comment]
Thanks! - I guess I have mostly got it.
