### ISSUE TITLE
How to insert &nbsp; ?

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#53]
...or any other entity? They are rendered literally.

**Comment by Kflash** [comment]
@gaydenko Any example?  And insert as what? Text node? HTML ?

**Comment by gaydenko** [comment]
@Kflash , just take any jsfiddle with any string :) Say, let's take http://jsfiddle.net/jpyr2ksL/81/ and replace the first child with `"Head&nbsp;line"`. Then we shell get literally the same on the rendered page. That is, XML-escaping has escaped ampersand, I guess. So, the question is how render text without escaping?

**Comment by Kflash** [comment]
@gaydenko I'm maybe to tired here. All escaping should only happen if you do server - side rendring, But, you mean something like this: http://jsfiddle.net/jpyr2ksL/92/
Just note that nothing are escaped unless you do something server-side.

**Comment by gaydenko** [comment]
@Kflash , I haven't understood. I'd want `"Head&nbsp;line"` to be rendered as  `Head line` rather than `Head&nbsp;line` . `Trackira.Text` has got:
```js
    toHTML() {
        return escapeHtml(this.text);
    }
```
I'd want at some special case to avoid this escaping.

**Comment by Kflash** [comment]
Ah okey, you are now doing server side rendring. That help me a bit :) Just hold on for a few minutes.

**Comment by gaydenko** [comment]
> you are now doing server side rendring

I use browser JS engine exclusively :)

**Comment by Kflash** [comment]
@gaydenko  Grab the latest update.

I changed the line to:
` return escape ? escapeHtml( this.text ) : this.text; ` 

so now if you need to escape any text, you have to pass in **true** as an argument, else nothing get escaped:

``` .toHTML(true) // escaping virtual text nodes ```

**Comment by gaydenko** [comment]
@Kflash , I have edited my previous message. The thing is, I use client-side only. And it was just my suggestion that `toHTML` is used on the client side as far as I have noticed call to escape function. Apparently, there are some other place with escaping text element on the client side also.

**Comment by Kflash** [comment]
It's impossible that the text get escaped on the client-side. The escaping are only server-side.

Take a look at this lines:

https://github.com/trackira/trackira/blob/master/dist/trackira.js#L120-L122

https://github.com/trackira/trackira/blob/master/dist/trackira.js#L702

This is the only 2 places in the whole code where I'm doing escaping - all server-side. Except for virtual comments:

https://github.com/trackira/trackira/blob/master/dist/trackira.js#L208-L210

again server-side.

**Comment by gaydenko** [comment]
> Meaning if you do pass in a text as an virtual text node, the output will become exactly what you send in to that function. No transformation.

So, how would you render a text fragment when it must contain more than a single space in between two symbols?

**Comment by Kflash** [comment]
I got your point. Give me some minutes.

**Comment by Kflash** [comment]
@gaydenko I have no good answers for you regarding this. This is all native browser behaviour, and nothing to do with Trackira.  Let me take an example:

` var foo = document.createTextNode("   hello,    world      "); `

If you look at this in the console, you would see it has multiple spaces. However, the magic happen if you do a `appendChild`. Multiple spaces are all gone.

**Comment by gaydenko** [comment]
@Kflash , I have found a hint - just to replace `&nbsp;` with  `\xA0`.

**Comment by Kflash** [comment]
@gaydenko I also found a hint, because I hate users of my script to get trouble even if it's out of the scope of what I'm doing :) Solution: Use unicode literals.

`` var foo = document.createTextNode("/u00A0"); ```

**Comment by gaydenko** [comment]
@Kflash , agree, Unicode notation can be more reliable at the case.

**Comment by Kflash** [comment]
@gaydenko In case you still have issues here, have a look at this demo: https://github.com/trackira/trackira/blob/master/demo/multiple_spaces.html

**Comment by gaydenko** [comment]
@Kflash , the problem is resolved. I use a couple of one-liners:
```js
  ...
  sp(count = 1) { return utl.repeat('\u00A0', count); },
  raw(s = '') { return s.replace(/ /g, `\u00A0`); },
  ...
```
