### ISSUE TITLE
checkbox input handler get empty sting instead of true

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#54]
checkbox change event handler get two parameters from Trackira - event and value. The last one is false for unchecked state and empty string for checked state. I guess it is more expected to pass true rather than empty string.

**Comment by Kflash** [comment]
@gaydenko Can you jsFiddle this? I'm guessing you are in the `genericHandler`

**Comment by Kflash** [comment]
@gaydenko I couldn't sleep before I figure out what you wanted me too to. And it was hard without any jsFiddle :)  Anyway. can you confirm that the problem are solved now?

**Comment by gaydenko** [comment]
@Kflash , sorry for delay, I was turned of by Morpheus :) I'll prepare a jsFiddle a bit later.

**Comment by Kflash** [comment]
I thought this was fixed now?

**Comment by gaydenko** [comment]
@Kflash , 
Have tried with current git master - yes, the issue has gone, thanks!

**Comment by gaydenko** [comment]
@Kflash , I use alocal repo soft-linked into `node_modules`, so it is just a matter of `git pull`.

**Comment by Kflash** [comment]
Ok. Anyhow. I managed to push to NPM now.
