### ISSUE TITLE
events: { "evt1 evt2": [handler1, handler2] }

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#55]
Hi!

I guess it would be handy to add to  `events` assigning a support for

1. Multiple events (separated by space) as an object key. Use case: validation handler can be interested, say, in both `changed` and `blur` events.

2. Multiple handlers as a value. Use case: `changed` event can be used both by validation handler and, say, for presenting some kind of "total" field (that is a computed field dependent from the field we are attaching handlers to).

**Comment by Kflash** [comment]
Right now - even I understand your point of view - I don't see any revelant use case where having multiple handler for a single event may be interesting. Furthermore, you won't be able to take advantage of if your higher abstraction is based on an html template or similar.
For example in angular there's some directives like `ng-click` which specify custom behavior when an element is clicked.
`<div  ng-click="expression"></div>`
Imagine that this kind of template can be automatically transformed into a valid virtual tree. However you won't be able to deal with something like `<div ng-click="expression1" ng-click="expression2"></div>` since you can't have two attribute with the same name.

**Comment by gaydenko** [comment]
@Kflash ,

Say, we have field "amount", and a user enters a number. On every key press (or key up) it can be needed to do two actions:

1. Control the field is valid (that is, for example, it is positive number),
2. Show "total" information.

At any case, it is just a suggestion (more strictly - two suggestions), and keeping all as is would not be a show stopper at all.

And, at any case, my code is *not* template-oriented in any sense absolutely :)

**Comment by deamme** [comment]
@gaydenko Why not call two functions instead?

**Comment by gaydenko** [comment]
> Why not call two functions instead?

It would result in additional verbosity. Ans, as I have already mentioned, keeping all as is isn't a show stopper. The issue is just a suggestion to discuss.

**Comment by Kflash** [comment]
@gaydenko I actually plan to handle all this and much more in my upcoming changes after my vacation. It's only a matter of time before I can return back home and fix this things.

**Comment by deamme** [comment]
@gaydenko I would not like additional code just for that. I like the way you keep suggestion things though, keep the good work :D!

**Comment by gaydenko** [comment]
@Kflash , so, shell we keep the issue opened in the meantime?

> and much more

I very hope not toooooo much :)

**Comment by Kflash** [comment]
In many places with Trackira I feel handicapped. But after all this is a low-end library with main focus on handling batching/diffing virtual DOM. So there will be changes like you mentioned here soon, how CSS are handled with auto-prefixing, etc. Yup. You can have it open for now.

**Comment by Kflash** [comment]
@gaydenko Can you join on Slack?

**Comment by gaydenko** [comment]
What is the Slack conversation name?

**Comment by Kflash** [comment]
@gaydenko See readme. https://trackira.slack.com and you find me there.

**Comment by gaydenko** [comment]
@Kflash , hm, can not understand how to join. Must my email be added to the team?

**Comment by Kflash** [comment]
@gaydenko Not  to team, but for registration. Should I send you an invite ?

**Comment by gaydenko** [comment]
I don't know that rules and there isn't any explaining on the site. If you ask about invite, probably, yes :)
andrew.gaydenko on gmail.

**Comment by Kflash** [comment]
Just check your email

**Comment by gaydenko** [comment]
I"m already was there :)

**Comment by gaydenko** [comment]
The issue is fixed in trunk, thanks!

**Comment by gaydenko** [comment]
After some thoughts and playing with code I have decided suggested sugar must be implemented in the code using Trackira, rather than in Trackira itself. It's better to keep the last one as light and compact as possible, to my taste.

So, closing the issue.

**Comment by Kflash** [comment]
Ok. I just closed this one then.
