### ISSUE TITLE
blur isn't triggered

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#56]
Hi!

This is slightly modified example form README.ms: http://jsfiddle.net/anli/jpyr2ksL/105/
Just click on input field and then click outside it - nothing happens.

**Comment by Kflash** [comment]
@gaydenko I will fix this as soon as I can. Is this urgent? I'm in the middle of a job for a client.

**Comment by gaydenko** [comment]
@Kflash , please, fix it at the time a fixing will be comfortable for you - nothing urgent.

**Comment by Kflash** [comment]
@gaydenko I have started to look into this, and it will be sorted out soon. But be aware that I'm playing with the thoughts of let Trackira die! However there will come an replacement with the same name, and you will still be able to use your pipe. But the API will change some.

Not sure where the head are going right now. But no panic. There are many users of Trackira, so I can't let anyone down. I probably will only maintain Trackira if issues popups and focus on what I'm doing now with a new name.

**Comment by gaydenko** [comment]
> But the API will change some

@Kflash , thanks for letting to know in advance :)

**Comment by Kflash** [comment]
@gaydenko I tried to solve the issue. Not so easy. Anyway. A new version is up with a few other changes.

**Comment by gaydenko** [comment]
@Kflash , thanks! - verified.
