### ISSUE TITLE
`attached` hook

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#57]
@Kflash , hi!
`created` hook is calling when an element is just created only. I'd want to get a hook when an element is attached to DOM also. There are two ways:

1. Change a point `created` hook is called,
2. Add new hook.

I prefer the first way. What do you think?

**Comment by Kflash** [comment]
@gaydenko Hi. I will do it as soon as I can. I have some teachings to do for a class whole next week, so I need to use this weekend to prepear myself. But I will handle it as soon as I got time here.

**Comment by gaydenko** [comment]
@Kflash , OK, I'm all in hope :) At the moment I use dirty hack - just recursively check (with `setTimeout`) element's parent existence every 200 mS (interaction with widget demands element's parent existence). It works, but it's really dirty.

**Comment by Kflash** [comment]
@gaydenko Can you ask @deamme to fix this if it needed to be done today? I think he have the skills for it. Sorry to say, but I'm occupied with my job that will take all my time now.  But I understand your problem.

**Comment by gaydenko** [comment]
> if it needed to be done today?

No-no, nothing urgent. As far as a temporary workaround is found, it is possible to move further :)

**Comment by Kflash** [comment]
I will address this issue as soon as I can. What kind of hooks you exactly need in the future? Maybe I can add a bunch of them in fixzi in the future.

**Comment by gaydenko** [comment]
At the moment I don't see any additional hooks I would be happy to add. That is just to modify `created` hook call point would be sufficient. 

Of course, I can't predict. There are still few subtle library-level moments not written in the way of integration Trackira into a project in hand.

**Comment by gaydenko** [comment]
Closing the issue as far as Trackira has got `children` hook in v.0.2.3a.
