### ISSUE TITLE
key using results in flickering

### ISSUE THREAD

**Issue by gaydenko** [trackira/trackira#58]
Hi!

The use case in hands is a SPA with pagination. At first I haven't used `key` for items rendered on this page, but at some point I have noticed a rendering error and have added unique keys to page items. The error has gone, but result seems to be a show stopper :( - a flickering takes place. Visually it can be imagined as a page is quickly collapses in vertical dimension, and then quickly expands. So, for example, bottom jumps up and then down. Without `key` using pagination looks absolutely smooth with frozen bottom (at case page items have the same height which is almost always).

On pagination step `update()` is called once, of course.

Is it possible to make patching process with keys as smooth as it is without keys?

**Comment by gaydenko** [comment]
Some additional information - not sure it will be useful, but as a mental hook :) Each page item (that is an item with unique `key`) has a container element based on CSS transition with initial `style.maxHeight` value set to zero in `created` hook. If I comment this fragment out, flickering is gone.

**Comment by Kflash** [comment]
@gaydenko Hi. I will look into this soon. The last days I have had anough of things to do offline. And still not done yet. Regarding the problem, I can't see how CSS are related to this, and can force a flicker issue. But there seems to be an issue with the diff/patching algorithm - the place where the keys are used. There will be an solution on the issue soon, but I can't give a schedule for it, or how I'm going to solve it. 

But something are going to happen soon...

**Comment by gaydenko** [comment]
@Kflash , OK, if I"m not sleeping, I'm ready to try commit you will direct me to.

**Comment by Kflash** [comment]
@gaydenko Could you tell me what exactly you are doing when this key issue happened? In the patching or?

**Comment by gaydenko** [comment]
@Kflash , I just get AJAX data for, say, the next page, and then call `update()`. Tree is linked with rendering function bound to my context. Then I map got data items to keyed `div`s:
```
items.map(i => h('div', {key: i.someUniquerIndex}, [ 
    ...some content...
    ...element with maxHeight set to zero and overflow to hidden in `created` hook...
]))
```

**Comment by Kflash** [comment]
@gaydenko Ok. Because of you calling `update()`, you are triggering update of the elements children. This algorithm handles the key nodes that seem to be the issue here. But why it can has so big impact, I'm not sure. But probably because the iteration are slower then other parts.

**Comment by Kflash** [comment]
@gaydenko I tried quickly to stabilize the issue now, so grab latest. Anyhow. This is a issue that need a lot of refactoring. I will look into it again soon as I get time for it.

**Comment by gaydenko** [comment]
@Kflash , I don't see new commit at the moment.

**Comment by gaydenko** [comment]
@Kflash , aha, have got the last commit. The issue still exists (and is gone without keying).

**Comment by Kflash** [comment]
@gaydenko Then there are only one solution... Can we move the conversation to Slack?

**Comment by gaydenko** [comment]
@Kflash , yes, we can.

**Comment by gaydenko** [comment]
After some thoughts I have got a conclusion: ) It isn't Trackira's matter to deal with the issue, as far as, saying formally, rendering is correct. So, closing the issue.

P.S. I have found a way to workaround the issue, and it is a playing with CSS too bound to complicated  context to describe details.
